### ISSUE TITLE
bug: Нет archives.rss и надо проверить корректность podcast.rss

### ISSUE THREAD

**Issue by ufian** [podcast-uwp/site#18]
Я покликал в интерфейсе и что-то podcast.rss вызывает подозрение на свою валидность 

![image](https://user-images.githubusercontent.com/1496873/46962980-5d40e180-d059-11e8-875d-e2bab0f01621.png)

**Comment by umputun** [comment]
а что именно вызывает подозрения? Отформатированный текс правильно сидит в CDATA, тэги вроде закрыты. На беглый взгляд я не вижу ничего явно неправильного

**Comment by umputun** [comment]
по поводу archives.rss - согласно [этому](https://github.com/umputun/podcast-uwp/blob/master/hugo/generate_rss.py#L25) оно должно делать `podcast-archives.rss` и `podcast-archives-short.rss`

**Comment by ufian** [comment]
Меня смущает, что цветовое выделение CDATA не забрала html код в себя + opera не смогла показать ничего на основе этого фида (я пристально не смотрел). Вечером проверю аккуратнее и поправлю `podcast-archives.rss` -> `archives.rss`, потому что страница с фидами имеет ссылку на последнее.

**Comment by umputun** [comment]
http://castfeedvalidator.com/?url=https://uwp.umputun.com/podcast.rss

**Comment by umputun** [comment]
вообще-то есть один недочет - нет размера файла

**Comment by ufian** [comment]
Для оригинального фида https://podcast.umputun.com/archives.rss размера файла тоже не было.

**Comment by umputun** [comment]
я про podcast.rss, там size=True https://github.com/umputun/podcast-uwp/blob/master/hugo/generate_rss.py#L22

для архивов там False чтоб не тормозить на каждом файле когда их 4е сотни

**Comment by ufian** [comment]
Я вижу, что size=True, но этот размер не учитывается в шаблоне, потому что я пытался воспроизвести старый фид один-в-один.

Посмотрел diff-ом разницу между https://podcast.umputun.com/podcast.rss https://uwp.umputun.com/podcast.rss 
Там куча мелких ошибок, вечером поправлю

**Comment by umputun** [comment]
если размер можно и несложно починить, то стоит пойти на эту несовместимость т.к. его отсутствие это был баг и не есть хорошо если/когда этот фид будем раздавать напрямую для подписки

**Comment by umputun** [comment]
как наше состояние с фидами? Вроде это последнее критическое изменение и если все в порядке, то я бы сегодня переключил сайт

**Comment by ufian** [comment]
Старый firefox показывает всё хорошо, guid вроде сохранился так что ленту подкаста поломать не должны.
