### ISSUE TITLE
Мелкие проблемы со стилями

### ISSUE THREAD

**Issue by umputun** [podcast-uwp/site#25]
<img width="252" alt="1rh25_20181016_231531 c1mxg" src="https://user-images.githubusercontent.com/535880/47061971-82d50480-d199-11e8-9859-875abee9f334.png">

<img width="251" alt="zfxio_20181016_231653 8wagl" src="https://user-images.githubusercontent.com/535880/47062012-a730e100-d199-11e8-87b3-e910371fd046.png">

<img width="171" alt="vr9xl_20181016_231749 w59zg" src="https://user-images.githubusercontent.com/535880/47062050-cb8cbd80-d199-11e8-9e7f-3dc336267d06.png">

**Comment by umputun** [comment]
<img width="483" alt="nipk4_20181017_000425 u8ig5" src="https://user-images.githubusercontent.com/535880/47063339-42c55000-d1a0-11e8-8318-013910bbe7d3.png">

**Comment by umputun** [comment]
#26 починил первые 2 проблемы, но последняя осталась. можно, наверное уменьшить размер фонта для этих prev/next ссылок

**Comment by reeywhaar** [comment]
Там какой-то очень странный баг в сафари. Если нажать левой кнопкой мыши, то там вообще рендеринг сходит с ума.
![screen shot 2018-10-17 at 23 15 54](https://user-images.githubusercontent.com/884649/47115662-ed547600-d267-11e8-8a7a-6286f979b68c.png)

**Comment by umputun** [comment]
<img width="610" alt="3vf4x-201810-17173406-seqr2" src="https://user-images.githubusercontent.com/535880/47120027-e5c6aa00-d232-11e8-8c29-c29a85022a7e.png">

сильно уменьшился фонт и строка меты опустилась вниз
