### ISSUE TITLE
Миграция фидов подкаста

### ISSUE THREAD

**Issue by ufian** [podcast-uwp/site#6]
Миграция фидов подкаста. В идеале они должны быть идентичны.

**Comment by ufian** [comment]
@umputun я тут понял, что тупая копипаста генерации rss была плохой идеей. Поэтому мне хочется навести порядок.

1. Какие фиды подкаста ты берешь из hugo? Используешь ли ты generate_rss.py?
2. Есть 2 вида url для файлов `https://podcast.umputun.com/media/ump_podcast408.mp3` и `http://archive.rucast.net/uwp/media/ump_podcast408.mp3`. Первый имеет лимит по количеству хранимых выпусков, второй - видимо нет. Как правильно их использовать?
3. Шаблон типа такого https://github.com/radio-t/radio-t-site/blob/master/hugo/data/rss/podcast-archives.xml берет ссылку `{url}` на mp3 файл из `.md` описания, а enclosure смотрит на `archive.rucast.net` . Нужно ли сохранять такую же логику?

**Comment by umputun** [comment]
по поводу RSS вообще - по моему их можно делать в hugo без всяких сторнних скриптов. В том, что сейчас из октопреса никаких скриптов для этого нет, за исключением вот этого, что делает фид без https: 

```
wget https://podcast.umputun.com/categories/podcast/atom.xml -O /srv/octopress/public/atom-failback.xml
sed -i 's|https://podcast|http://podcast-failback|g' /srv/octopress/public/atom-failback.xml
``` 

> Какие фиды подкаста ты берешь из hugo? Используешь ли ты generate_rss.py?

это видимо про радиот? Насколько я помню там основной из hugo а архивы строятся из "build-rss-archive.py". Вроде еще где-то строился фид гиковских, но это, насколько я понимаю., тут нам не важно.

> Есть 2 вида url для файлов https://podcast.umputun.com/media/ump_podcast408.mp3 и http://archive.rucast.net/uwp/media/ump_podcast408.mp3. Первый имеет лимит по количеству хранимых выпусков, второй - видимо нет. Как правильно их использовать?

Эти ссылки показывают на одни и те же файлы, то что линки разны это, видимо, какие-то исторические причины. Там где лимит по количеству - это основной фид, где нет это архивы.

> Шаблон типа такого https://github.com/radio-t/radio-t-site/blob/master/hugo/data/rss/podcast-archives.xml берет ссылку {url} на mp3 файл из .md описания, а enclosure смотрит на archive.rucast.net . Нужно ли сохранять такую же логику?

я не настаиваю на такой логике если у тебя есть другие идеи как это строить проще.

**Comment by ufian** [comment]
Я переношу решения из radio-t, так проще и быстрее. Если можно rss генерить из hugo, то прекрасно, но мне быстрее поправить скрипты.

Решение тогда у меня будет такое:
1. Ограниченный фид будет с ссылками https://podcast.umputun.com/media/ump_podcast408.mp3
2. Оба архивных будут с ссылками http://archive.rucast.net/uwp/media/ump_podcast408.mp3

**Comment by umputun** [comment]
я почти на 100% уверен, что в радио-т основной rss строится hugo из этого https://github.com/radio-t/radio-t-site/blob/master/hugo/layouts/rss.xml

p.s. вообще и в радиот я эти скрипты не люблю и планирую от них избавится по возможности. Я бы рекомендовал генерить по максимуму все, что можно, самим hugo

**Comment by ufian** [comment]
Тогда правильный вопрос будет такой: используются ли где-то этот фид https://podcast.umputun.com/podcast.rss

А так же симетричные
http://radio-t.com/podcast.rss
http://radio-t.com/podcast-archives.rss
http://radio-t.com/podcast-archives-short.rss

Если нет, то тогда проще удалить.

P.S. Вопрос связан с тем, что все фиды на сайтах ссылаются на feedburner (feeds.rucast.net) и я не вижу, что у них в качестве источника.

**Comment by umputun** [comment]
все эти фиды были построенны примерно в одно и тоже время, когда появились опасения, что дни feedburner сочтены. Основной фид строится сейчас из feddburner на основе вот этого https://podcast.umputun.com/categories/podcast/atom.xml

А https://podcast.umputun.com/podcast.rss лучше оставить, т.к. никогда не знаешь что следущим гугл убьет.
